name: Daily Price Scraper

on:
  schedule:
    - cron: '30 16 * * *'  # 10 PM IST (4:30 PM UTC)
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || pip install requests beautifulsoup4 pandas

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push updates
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add *.csv
          git commit -m "Update CSV files with latest data" || echo "No changes to commit"
          git push
